%% Trabalho de Antenas
% 2021/04/07 - Lucas Abdalah
%
%
%% Limpar o ambiente do matlab
% close all; clearvars; clc;
%% Parte 1 - Antena Yagi-Uda
% Script generated by antennaDesigner 

%% General parameters
% Define plot frequency 
plotFrequency = 2000000000;
% Define frequency range 
freqRange = (1800:20:2200) * 1e6;


%% Numdir = 6 
% Load the yagiUda_antennaDesigner
load('yagiUda6_antennaDesigner'); % 6 dir
yagiUda6_antennaDesigner = yagiUda_antennaDesigner;
clear yagiUda_antennaDesigner
% Define antenna 
antennaObject = yagiUda6_antennaDesigner;
% show for yagiUda
figure;
show(antennaObject) 
% impedance for yagiUda
figure;
impedance(antennaObject, freqRange) 
% azimuth for yagiUda
figure;
patternAzimuth(antennaObject, plotFrequency) 
% elevation for yagiUda
figure;
patternElevation(antennaObject, plotFrequency) 
% s11 for yagiUda
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 

disp('>> Aperte qualquer tecla para visualizar a Yagi-Uda com 12 dir')
pause; 
close all;
%% Numdir = 12
load('yagiUda12_antennaDesigner'); % 12 dir
yagiUda12_antennaDesigner = yagiUda_antennaDesigner;
antennaObject = yagiUda12_antennaDesigner;

% show for yagiUda
figure;
show(antennaObject) 
% impedance for yagiUda
figure;
impedance(antennaObject, freqRange) 
% azimuth for yagiUda
figure;
patternAzimuth(antennaObject, plotFrequency) 
% elevation for yagiUda
figure;
patternElevation(antennaObject, plotFrequency) 
% s11 for yagiUda
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 

